Repository CjFanClub/CjNum1, pull requests merged in 2023-11, with the labels that each got.

#50 test_maintance
  test.html
Labels: chore

#52 测试
  test.html
Labels: fix

#57 機能追加_テスト
  test.html
Labels: 機能追加

#58 機能改善_テスト
  test.html
Labels: 機能改善

#59 不具合修正_テスト
  test.html
Labels: 不具合修正

#60 監視エラー_テスト
  test.html
Labels: 監視エラー

#64 Release at 2023.12.06
  .github/release-drafter.yml
  .github/workflows/create_staging_release.yml
Labels: release

#65 不具合修正 div
  test.html
Labels: 不具合修正

#66 Release at 2023.12.06
  test.html
Labels: release

#69 测试其他lable
  test.html
Labels: documentation

#79 test
  test.html
Labels: 不具合修正

#85 多ラベルtest
  test.html
Labels: 機能追加, 監視エラー

#83 機能改善test
  test.html
Labels: 機能改善

#80 不具合修正test
  test.html
Labels: 不具合修正
